/**
 * Workflow Notification Service
 *
 * Enqueues, processes, and manages notifications generated by
 * the workflow automation layer (SLA violations, reminders, expirations).
 *
 * Channels: EMAIL, IN_APP
 * Uses the workflow_notification_queue Supabase table.
 */

import { getSupabase } from "@/lib/db"
import { logger } from "@/lib/logger"

// ── Types ────────────────────────────────────────────────────────────────

export type NotificationChannel = "EMAIL" | "IN_APP"
export type RecipientType = "ADMIN" | "BUYER" | "DEALER" | "SYSTEM"
export type NotificationStatus = "PENDING" | "SENT" | "FAILED"

export interface EnqueueNotificationInput {
  channel: NotificationChannel
  recipientType: RecipientType
  recipientId?: string | null
  recipientEmail?: string | null
  templateKey: string
  subject?: string | null
  payload?: Record<string, unknown>
  sendAfter?: string | null // ISO timestamp
}

export interface WorkflowNotification {
  id: string
  channel: NotificationChannel
  recipient_type: RecipientType
  recipient_id: string | null
  recipient_email: string | null
  template_key: string
  subject: string | null
  payload: Record<string, unknown>
  status: NotificationStatus
  send_after: string
  sent_at: string | null
  error_message: string | null
  created_at: string
  updated_at: string
}

// ── Enqueue ──────────────────────────────────────────────────────────────

/**
 * Enqueue a workflow notification for later delivery.
 */
export async function enqueueNotification(
  input: EnqueueNotificationInput,
): Promise<WorkflowNotification | null> {
  try {
    if (!input.templateKey) {
      logger.warn("enqueueNotification: templateKey is required")
      return null
    }

    const supabase = getSupabase()

    const row = {
      channel: input.channel,
      recipient_type: input.recipientType,
      recipient_id: input.recipientId ?? null,
      recipient_email: input.recipientEmail ?? null,
      template_key: input.templateKey,
      subject: input.subject ?? null,
      payload: input.payload ?? {},
      status: "PENDING" as const,
      send_after: input.sendAfter ?? new Date().toISOString(),
    }

    const { data, error } = await supabase
      .from("workflow_notification_queue")
      .insert(row)
      .select()
      .single()

    if (error) {
      logger.error("Failed to enqueue workflow notification", {
        error: error.message,
        templateKey: input.templateKey,
      })
      return null
    }

    return data as WorkflowNotification
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err)
    logger.error("enqueueNotification unexpected error", { error: message })
    return null
  }
}

// ── Fetch pending ────────────────────────────────────────────────────────

/**
 * Fetch notifications that are due for delivery.
 */
export async function fetchPendingNotifications(
  limit = 50,
): Promise<WorkflowNotification[]> {
  try {
    const supabase = getSupabase()

    const { data, error } = await supabase
      .from("workflow_notification_queue")
      .select("*")
      .eq("status", "PENDING")
      .lte("send_after", new Date().toISOString())
      .order("send_after", { ascending: true })
      .limit(limit)

    if (error) {
      logger.error("Failed to fetch pending notifications", { error: error.message })
      return []
    }

    return (data ?? []) as WorkflowNotification[]
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err)
    logger.error("fetchPendingNotifications unexpected error", { error: message })
    return []
  }
}

// ── Mark sent / failed ───────────────────────────────────────────────────

/**
 * Mark a notification as successfully sent.
 */
export async function markNotificationSent(id: string): Promise<boolean> {
  try {
    const supabase = getSupabase()

    const { error } = await supabase
      .from("workflow_notification_queue")
      .update({
        status: "SENT",
        sent_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      })
      .eq("id", id)

    if (error) {
      logger.error("Failed to mark notification sent", { error: error.message, id })
      return false
    }

    return true
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err)
    logger.error("markNotificationSent unexpected error", { error: message, id })
    return false
  }
}

/**
 * Mark a notification as failed with an error message.
 */
export async function markNotificationFailed(
  id: string,
  errorMessage: string,
): Promise<boolean> {
  try {
    const supabase = getSupabase()

    const { error } = await supabase
      .from("workflow_notification_queue")
      .update({
        status: "FAILED",
        error_message: errorMessage,
        updated_at: new Date().toISOString(),
      })
      .eq("id", id)

    if (error) {
      logger.error("Failed to mark notification failed", { error: error.message, id })
      return false
    }

    return true
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err)
    logger.error("markNotificationFailed unexpected error", { error: message, id })
    return false
  }
}

// ── Process queue ────────────────────────────────────────────────────────

export interface ProcessResult {
  processed: number
  sent: number
  failed: number
}

/**
 * Process pending notifications in the queue.
 *
 * This is a lightweight dispatcher — it marks items as SENT after
 * logging intent. In production, integrate with Resend or the
 * in-app notification system here.
 */
export async function processNotificationQueue(
  limit = 50,
): Promise<ProcessResult> {
  const result: ProcessResult = { processed: 0, sent: 0, failed: 0 }

  const pending = await fetchPendingNotifications(limit)
  result.processed = pending.length

  for (const notification of pending) {
    try {
      // Channel-specific delivery logic (exhaustive switch)
      switch (notification.channel) {
        case "IN_APP":
          // In-app notifications are marked as SENT immediately;
          // the front-end polls the workflow_notification_queue table.
          await markNotificationSent(notification.id)
          result.sent++
          break

        case "EMAIL":
          // Email delivery placeholder — integrate with Resend here.
          // For now, mark as sent (actual email sending is a separate concern).
          logger.info("Email notification ready for delivery", {
            id: notification.id,
            templateKey: notification.template_key,
            recipientEmail: notification.recipient_email ? "[REDACTED]" : null,
          })
          await markNotificationSent(notification.id)
          result.sent++
          break

        default: {
          const _exhaustive: never = notification.channel
          await markNotificationFailed(notification.id, `Unknown channel: ${_exhaustive}`)
          result.failed++
        }
      }
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err)
      await markNotificationFailed(notification.id, message)
      result.failed++
    }
  }

  return result
}
